# This is a basic workflow to help you get started with Actions

name: test_action

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: test secret
        run: |
          echo ${{ secrets.TEST_ANTON }} >> ./test
          cat ./test

