# This is a basic workflow to help you get started with Actions

name: Check python code in PR

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies and pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f ./code/requirements.txt ]; then pip install -r ./code/requirements.txt; fi
      
      - name: Testing code
        id: pylint
        run: |
          echo ::set-output name=result::$(pylint ./code/*.py)

      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "python\n${{ steps.pylint.outputs.result }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Pylint test 🖌\`${{ steps.pylint.outcome }}\`
            <details><summary>Show Output</summary>
            \`\`\`${process.env.PLAN}\`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
        
      - name: test secret
        run: |
          echo ${{ secrets.TEST_ANTON }} >> ./test
          cat ./test

      #- name: Python Code Quality and Lint
      #  uses: ricardochaves/python-lint@v1.3.0
      #  with:
      #    # A list of all paths to test
      #    python-root-list: ./code/*.py
      #    use-pylint: true
      #    use-pycodestyle: false
      #    use-flake8: false
      #    use-black: false
      #    use-mypy: false
      #    use-isort: false

